/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — does not touch Postgres or Redis.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — checks Postgres and Redis.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List imported seasons
         * @description Seasons with at least one imported race, newest first.
         */
        get: operations["list_seasons_api_v1_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List imported races
         * @description Imported races (newest season first, then by round) with their sessions.
         */
        get: operations["list_races_api_v1_races_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get race metadata */
        get: operations["get_race_api_v1_races__race_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a race's drivers
         * @description Participants of one session of the event, ordered by abbreviation.
         */
        get: operations["list_race_drivers_api_v1_races__race_id__drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/laps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a race's historical laps
         * @description Complete historical laps (not limited by any replay), ordered by lap then driver.
         */
        get: operations["list_race_laps_api_v1_races__race_id__laps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get session metadata */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/laps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a session's historical laps */
        get: operations["list_laps_api_v1_sessions__session_id__laps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/stints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a session's tyre stints */
        get: operations["list_stints_api_v1_sessions__session_id__stints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/track-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a session's track status periods */
        get: operations["list_track_status_api_v1_sessions__session_id__track_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a replay
         * @description Create a replay (``CREATED``) for a session whose timeline has been generated.
         */
        post: operations["create_replay_api_v1_replays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get replay status */
        get: operations["get_replay_api_v1_replays__replay_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a created replay
         * @description ``CREATED`` → ``RUNNING``; any other status is 409 ``INVALID_REPLAY_TRANSITION``.
         */
        post: operations["start_replay_api_v1_replays__replay_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a running replay
         * @description ``RUNNING`` → ``PAUSED``.
         */
        post: operations["pause_replay_api_v1_replays__replay_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused replay
         * @description ``PAUSED`` → ``RUNNING``.
         */
        post: operations["resume_replay_api_v1_replays__replay_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a replay
         * @description ``RUNNING``/``PAUSED`` → ``STOPPED`` (terminal; use restart to run again).
         */
        post: operations["stop_replay_api_v1_replays__replay_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart a replay from the beginning
         * @description Any started status → ``RUNNING`` from race time 0 under a new run; keeps the speed.
         */
        post: operations["restart_replay_api_v1_replays__replay_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change playback speed
         * @description Allowed in any status; the virtual race position is preserved.
         */
        patch: operations["change_replay_speed_api_v1_replays__replay_id__speed_patch"];
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current race state
         * @description Authoritative race snapshot with drivers ordered by position.
         *
         *     409 ``REPLAY_NOT_STARTED`` before the replay starts; 404 ``RACE_STATE_UNAVAILABLE``
         *     when nothing has been processed yet. The final state stays available after completion.
         */
        get: operations["get_race_state_api_v1_replays__replay_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/drivers/{driver}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one driver's current state
         * @description Position, gaps, laps, tyres, pit status and recent laps of one driver.
         */
        get: operations["get_driver_state_api_v1_replays__replay_id__drivers__driver__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List detected events
         * @description Detections of a replay ordered by source sequence, event type and id.
         *
         *     ``driver`` matches either the primary or the secondary driver.
         */
        get: operations["list_detected_events_api_v1_replays__replay_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one detected event */
        get: operations["get_detected_event_api_v1_replays__replay_id__events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/timing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lap-by-lap timing series
         * @description Per-driver lap points (lap time, position, gap to leader, tyre, pit flags, sectors)
         *     for laps the replay has already released.
         */
        get: operations["get_replay_timing_api_v1_replays__replay_id__timing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays/{replay_id}/drivers/{driver}/timing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One driver's lap-by-lap timing series */
        get: operations["get_driver_timing_api_v1_replays__replay_id__drivers__driver__timing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a historical session
         * @description Import a historical session into the database (201 imported/replaced, 200 already
         *     imported). Operator endpoint: it downloads historical data and can be slow.
         */
        post: operations["import_race_api_v1_races_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Timeline Events */
        get: operations["list_timeline_events_api_v1_sessions__session_id__timeline_get"];
        put?: never;
        /**
         * Generate Timeline
         * @description Build and persist the historical timeline for an imported session.
         */
        post: operations["generate_timeline_api_v1_sessions__session_id__timeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/timeline/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline Summary */
        get: operations["get_timeline_summary_api_v1_sessions__session_id__timeline_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DetectedEventOut */
        DetectedEventOut: {
            /**
             * Detected Event Id
             * Format: uuid
             */
            detected_event_id: string;
            event_type: components["schemas"]["DetectedEventType"];
            /** Schema Version */
            schema_version: number;
            /**
             * Replay Id
             * Format: uuid
             */
            replay_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Race Id */
            race_id: string | null;
            /** Race Time Ms */
            race_time_ms: number;
            /** Lap Number */
            lap_number: number | null;
            /** Primary Driver Id */
            primary_driver_id: string | null;
            /** Primary Driver Abbreviation */
            primary_driver_abbreviation: string | null;
            /** Secondary Driver Id */
            secondary_driver_id: string | null;
            /** Secondary Driver Abbreviation */
            secondary_driver_abbreviation: string | null;
            severity: components["schemas"]["Severity"] | null;
            /** Confidence */
            confidence: number | null;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Source Event Ids */
            source_event_ids: string[];
            /** Source Sequence */
            source_sequence: number;
            /** Detector Name */
            detector_name: string;
            /** Detector Version */
            detector_version: number;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /** DetectedEventPageOut */
        DetectedEventPageOut: {
            /**
             * Replay Id
             * Format: uuid
             */
            replay_id: string;
            /**
             * Run Id
             * @description Run the items belong to (latest run by default)
             */
            run_id: string | null;
            /** Items */
            items: components["schemas"]["DetectedEventOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * DetectedEventType
         * @description Analytical events produced by the event detection engine.
         *
         *     Distinct from ``EventType`` (raw historical timeline events).
         * @enum {string}
         */
        DetectedEventType: "BATTLE_FORMING" | "RAPIDLY_CLOSING" | "OVERTAKE" | "PACE_DEGRADATION" | "PACE_ANOMALY" | "PERSONAL_BEST" | "NEW_STINT";
        /**
         * DriverRaceStatus
         * @enum {string}
         */
        DriverRaceStatus: "NOT_STARTED" | "RUNNING" | "FINISHED" | "DID_NOT_FINISH";
        /** DriverState */
        DriverState: {
            /**
             * Driver Id
             * Format: uuid
             */
            driver_id: string;
            /** Abbreviation */
            abbreviation: string;
            /** Driver Number */
            driver_number?: number | null;
            /** Full Name */
            full_name?: string | null;
            /** Team Name */
            team_name?: string | null;
            /** Grid Position */
            grid_position?: number | null;
            /** Position */
            position?: number | null;
            /** Previous Position */
            previous_position?: number | null;
            /**
             * Laps Completed
             * @default 0
             */
            laps_completed: number;
            /** Current Lap */
            current_lap?: number | null;
            /** Last Lap Time Ms */
            last_lap_time_ms?: number | null;
            /** Last Lap Race Time Ms */
            last_lap_race_time_ms?: number | null;
            /** Best Lap Time Ms */
            best_lap_time_ms?: number | null;
            /** Best Lap Number */
            best_lap_number?: number | null;
            /** Gap To Leader Ms */
            gap_to_leader_ms?: number | null;
            /** Interval To Ahead Ms */
            interval_to_ahead_ms?: number | null;
            gap_basis?: components["schemas"]["GapBasis"] | null;
            /** Laps Behind Leader */
            laps_behind_leader?: number | null;
            /** Compound */
            compound?: string | null;
            /** Tyre Age Laps */
            tyre_age_laps?: number | null;
            /** Stint Number */
            stint_number?: number | null;
            /** Tyre Info Lap */
            tyre_info_lap?: number | null;
            /** @default UNKNOWN */
            pit_status: components["schemas"]["PitStatus"];
            /**
             * Pit Stop Count
             * @default 0
             */
            pit_stop_count: number;
            /** Last Pit Entry Lap */
            last_pit_entry_lap?: number | null;
            /** Last Pit Entry Race Time Ms */
            last_pit_entry_race_time_ms?: number | null;
            /** Last Pit Exit Race Time Ms */
            last_pit_exit_race_time_ms?: number | null;
            /** Last Pit Lane Duration Ms */
            last_pit_lane_duration_ms?: number | null;
            /** @default NOT_STARTED */
            race_status: components["schemas"]["DriverRaceStatus"];
            /** Recent Laps */
            recent_laps?: components["schemas"]["LapRecord"][];
        };
        /** DriverStateResponse */
        DriverStateResponse: {
            /**
             * Replay Id
             * Format: uuid
             */
            replay_id: string;
            replay_status: components["schemas"]["ReplayStatus"];
            source: components["schemas"]["StateSource"];
            phase: components["schemas"]["RacePhase"];
            /** Current Race Time Ms */
            current_race_time_ms: number;
            /** Current Lap */
            current_lap: number | null;
            /** Last Sequence */
            last_sequence: number;
            driver: components["schemas"]["DriverState"];
        };
        /** DriverSummary */
        DriverSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Driver Number */
            driver_number: number | null;
            /** Abbreviation */
            abbreviation: string;
            /** Full Name */
            full_name: string;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Team Name */
            team_name: string | null;
            /** Grid Position */
            grid_position: number | null;
            /** Finish Position */
            finish_position: number | null;
            /** Result Status */
            result_status: string | null;
        };
        /** DriverTimingResponse */
        DriverTimingResponse: {
            /**
             * Replay Id
             * Format: uuid
             */
            replay_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Upto Sequence */
            upto_sequence: number | null;
            /** Lap From */
            lap_from: number | null;
            /** Lap To */
            lap_to: number | null;
            driver: components["schemas"]["DriverTimingSeries"];
        };
        /** DriverTimingSeries */
        DriverTimingSeries: {
            /**
             * Driver Id
             * Format: uuid
             */
            driver_id: string;
            /** Abbreviation */
            abbreviation: string;
            /**
             * Points
             * @description Ordered by lap number
             */
            points: components["schemas"]["TimingPoint"][];
        };
        /**
         * ErrorResponse
         * @description Body of every non-2xx response.
         */
        ErrorResponse: {
            /**
             * Code
             * @description Stable machine-readable error code
             * @example REPLAY_NOT_FOUND
             */
            code: string;
            /**
             * Message
             * @description Human-readable, client-safe description
             */
            message: string;
            /**
             * Details
             * @description Optional structured context
             */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * EventType
         * @description Machine-readable race event types.
         * @enum {string}
         */
        EventType: "RACE_STARTED" | "LAP_COMPLETED" | "SECTOR_COMPLETED" | "POSITION_CHANGED" | "PIT_ENTRY" | "PIT_EXIT" | "FASTEST_LAP" | "TRACK_STATUS_CHANGED" | "BATTLE_FORMING" | "PACE_DEGRADATION" | "PACE_ANOMALY";
        /** FastestLap */
        FastestLap: {
            /**
             * Driver Id
             * Format: uuid
             */
            driver_id: string;
            /** Abbreviation */
            abbreviation?: string | null;
            /** Lap Number */
            lap_number?: number | null;
            /** Lap Time Ms */
            lap_time_ms: number;
            /** Race Time Ms */
            race_time_ms: number;
        };
        /**
         * GapBasis
         * @enum {string}
         */
        GapBasis: "LAP_END";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe response.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LapOut */
        LapOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Driver Abbreviation */
            driver_abbreviation: string;
            /** Lap Number */
            lap_number: number;
            /** Lap Time Ms */
            lap_time_ms: number | null;
            /** Position */
            position: number | null;
            /** Compound */
            compound: string | null;
            /** Tyre Age Laps */
            tyre_age_laps: number | null;
            /** Stint Number */
            stint_number: number | null;
            /** Is Deleted */
            is_deleted: boolean | null;
            /** Is Accurate */
            is_accurate: boolean | null;
            /** Lap Start Time Ms */
            lap_start_time_ms: number | null;
            /** Lap End Time Ms */
            lap_end_time_ms: number | null;
            /** Pit In Time Ms */
            pit_in_time_ms: number | null;
            /** Pit Out Time Ms */
            pit_out_time_ms: number | null;
            /** Is Pit In Lap */
            is_pit_in_lap: boolean;
            /** Is Pit Out Lap */
            is_pit_out_lap: boolean;
            /** Pit Duration Ms */
            pit_duration_ms: number | null;
            /** Sectors */
            sectors: components["schemas"]["SectorOut"][];
        };
        /** LapPage */
        LapPage: {
            /** Items */
            items: components["schemas"]["LapOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** LapRecord */
        LapRecord: {
            /** Lap Number */
            lap_number: number;
            /** Lap Time Ms */
            lap_time_ms?: number | null;
            /** Position */
            position?: number | null;
            /** Compound */
            compound?: string | null;
            /** Tyre Age Laps */
            tyre_age_laps?: number | null;
            /** Stint Number */
            stint_number?: number | null;
            /** Is Pit In Lap */
            is_pit_in_lap?: boolean | null;
            /** Is Pit Out Lap */
            is_pit_out_lap?: boolean | null;
            /** Is Deleted */
            is_deleted?: boolean | null;
            /** Is Accurate */
            is_accurate?: boolean | null;
            /** Track Status */
            track_status?: string | null;
            /** Race Time Ms */
            race_time_ms: number;
            /** Completion Time Source */
            completion_time_source?: string | null;
        };
        /**
         * PitStatus
         * @enum {string}
         */
        PitStatus: "UNKNOWN" | "IN_PIT" | "ON_TRACK";
        /** RaceDetail */
        RaceDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Name */
            name: string;
            /** Official Name */
            official_name: string | null;
            /** Country */
            country: string | null;
            /** Location */
            location: string | null;
            /** Event Date */
            event_date: string | null;
            /**
             * Sessions
             * @description Imported sessions of the event
             */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /**
         * RaceImportRequest
         * @description Request body for importing a historical session via FastF1.
         */
        RaceImportRequest: {
            /**
             * Season
             * @description Championship season year
             */
            season: number;
            /**
             * Round
             * @description Championship round number
             */
            round?: number | null;
            /**
             * Event Name
             * @description FastF1 event name
             */
            event_name?: string | null;
            /** @default RACE */
            session_type: components["schemas"]["SessionType"];
            /**
             * Replace
             * @description When true, rebuild an already-imported session
             * @default false
             */
            replace: boolean;
        };
        /**
         * RaceImportResponse
         * @description Result of a race session import.
         */
        RaceImportResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "imported" | "already_imported" | "replaced";
            /**
             * Race Id
             * Format: uuid
             */
            race_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Event Name */
            event_name: string;
            session_type: components["schemas"]["SessionType"];
            /** Driver Count */
            driver_count: number;
            /** Lap Count */
            lap_count: number;
            /** Sector Count */
            sector_count: number;
            /** Stint Count */
            stint_count: number;
            /** Track Status Count */
            track_status_count: number;
            /** Warnings */
            warnings: string[];
            /** Skipped Count */
            skipped_count: number;
        };
        /**
         * RacePhase
         * @enum {string}
         */
        RacePhase: "PRE_RACE" | "RUNNING" | "CHEQUERED" | "COMPLETED";
        /** RaceStateResponse */
        RaceStateResponse: {
            /**
             * Replay Id
             * Format: uuid
             */
            replay_id: string;
            replay_status: components["schemas"]["ReplayStatus"];
            /** @description 'live' (Redis) or 'snapshot' (PostgreSQL fallback) */
            source: components["schemas"]["StateSource"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Race Id */
            race_id: string | null;
            /** Season */
            season: number | null;
            /** Round */
            round: number | null;
            /** Session Type */
            session_type: string | null;
            phase: components["schemas"]["RacePhase"];
            /** Current Race Time Ms */
            current_race_time_ms: number;
            /**
             * Current Lap
             * @description Lap the leader is on
             */
            current_lap: number | null;
            /** Total Laps */
            total_laps: number | null;
            /** Leader Laps Completed */
            leader_laps_completed: number;
            /** Leader Driver Id */
            leader_driver_id: string | null;
            /** Leader Driver Abbreviation */
            leader_driver_abbreviation: string | null;
            track_status: components["schemas"]["TrackStatus"] | null;
            fastest_lap: components["schemas"]["FastestLap"] | null;
            /**
             * Last Sequence
             * @description Sequence of the last applied timeline event
             */
            last_sequence: number;
            /** Last Event Id */
            last_event_id: string | null;
            /** Total Events */
            total_events: number;
            /** Updated At */
            updated_at: string | null;
            /**
             * Drivers
             * @description Ordered by position
             */
            drivers: components["schemas"]["DriverState"][];
        };
        /** RaceSummary */
        RaceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Name */
            name: string;
            /** Official Name */
            official_name: string | null;
            /** Country */
            country: string | null;
            /** Location */
            location: string | null;
            /** Event Date */
            event_date: string | null;
            /**
             * Sessions
             * @description Imported sessions of the event
             */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /**
         * ReadinessChecks
         * @description Individual dependency check results.
         */
        ReadinessChecks: {
            /**
             * Postgres
             * @enum {string}
             */
            postgres: "ok" | "error";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
        };
        /**
         * ReadinessResponse
         * @description Readiness probe response.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** @description Dependency check results */
            checks: components["schemas"]["ReadinessChecks"];
        };
        /** ReplayCreateRequest */
        ReplayCreateRequest: {
            /**
             * Session Id
             * Format: uuid
             * @description Session to replay (its timeline must be generated)
             */
            session_id: string;
            /**
             * Playback Speed
             * @description Supported: 1, 2, 5, 10, 20
             * @default 1
             */
            playback_speed: number | string;
        };
        /** ReplayResponse */
        ReplayResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Race Id
             * Format: uuid
             */
            race_id: string;
            status: components["schemas"]["ReplayStatus"];
            /**
             * Is Completed
             * @description True once the whole timeline has been replayed
             */
            is_completed: boolean;
            /** Status Reason */
            status_reason: string | null;
            /** Playback Speed */
            playback_speed: number;
            /**
             * Current Race Time Ms
             * @description Virtual race clock position
             */
            current_race_time_ms: number;
            /**
             * Current Sequence
             * @description Sequence of the last emitted event
             */
            current_sequence: number | null;
            /** Emitted Event Count */
            emitted_event_count: number;
            /** Total Events */
            total_events: number | null;
            /**
             * Current Lap
             * @description Race lap the leader is on
             */
            current_lap: number | null;
            /** Total Laps */
            total_laps: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Paused At */
            paused_at: string | null;
            /** Ended At */
            ended_at: string | null;
        };
        /** ReplaySpeedRequest */
        ReplaySpeedRequest: {
            /**
             * Playback Speed
             * @description Supported: 1, 2, 5, 10, 20
             */
            playback_speed: number | string;
        };
        /**
         * ReplayStatus
         * @description Replay session lifecycle status (transitions live in ``app.replay.state``).
         * @enum {string}
         */
        ReplayStatus: "CREATED" | "RUNNING" | "PAUSED" | "STOPPED" | "COMPLETED" | "FAILED";
        /** ReplayTimingResponse */
        ReplayTimingResponse: {
            /**
             * Replay Id
             * Format: uuid
             */
            replay_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Upto Sequence
             * @description Only laps released by the replay up to this timeline sequence are included
             */
            upto_sequence: number | null;
            /** Lap From */
            lap_from: number | null;
            /** Lap To */
            lap_to: number | null;
            /**
             * Drivers
             * @description Ordered by abbreviation
             */
            drivers: components["schemas"]["DriverTimingSeries"][];
        };
        /** SeasonSummary */
        SeasonSummary: {
            /** Season */
            season: number;
            /**
             * Race Count
             * @description Imported races in the season
             */
            race_count: number;
        };
        /** SectorOut */
        SectorOut: {
            /** Sector Number */
            sector_number: number;
            /** Sector Time Ms */
            sector_time_ms: number | null;
        };
        /** SessionCounts */
        SessionCounts: {
            /** Laps */
            laps: number;
            /** Sectors */
            sectors: number;
            /** Stints */
            stints: number;
            /** Track Status Periods */
            track_status_periods: number;
        };
        /** SessionDetail */
        SessionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Race Id
             * Format: uuid
             */
            race_id: string;
            session_type: components["schemas"]["SessionType"];
            /** Name */
            name: string;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Drivers */
            drivers: components["schemas"]["DriverSummary"][];
            counts: components["schemas"]["SessionCounts"];
        };
        /** SessionSummary */
        SessionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            session_type: components["schemas"]["SessionType"];
            /** Name */
            name: string;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
        };
        /**
         * SessionType
         * @description Grand Prix weekend session types.
         * @enum {string}
         */
        SessionType: "PRACTICE_1" | "PRACTICE_2" | "PRACTICE_3" | "QUALIFYING" | "SPRINT_QUALIFYING" | "SPRINT" | "RACE";
        /**
         * Severity
         * @description Coarse magnitude of a detection, only where a detector documents its bands.
         * @enum {string}
         */
        Severity: "LOW" | "MEDIUM" | "HIGH";
        /**
         * StateSource
         * @enum {string}
         */
        StateSource: "live" | "snapshot";
        /** StintOut */
        StintOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Driver Abbreviation */
            driver_abbreviation: string;
            /** Stint Number */
            stint_number: number;
            /** Compound */
            compound: string;
            /** Start Lap */
            start_lap: number;
            /** End Lap */
            end_lap: number | null;
            /** Tyre Age At Start */
            tyre_age_at_start: number | null;
        };
        /** TimelineEventOut */
        TimelineEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sequence */
            sequence: number;
            event_type: components["schemas"]["EventType"];
            /** Race Time Ms */
            race_time_ms: number | null;
            /** Lap Number */
            lap_number: number | null;
            /** Driver Id */
            driver_id: string | null;
            /** Driver Abbreviation */
            driver_abbreviation: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** TimelineEventPage */
        TimelineEventPage: {
            /** Items */
            items: components["schemas"]["TimelineEventOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** TimelineGenerateRequest */
        TimelineGenerateRequest: {
            /**
             * Regenerate
             * @default false
             */
            regenerate: boolean;
        };
        /** TimelineSummaryResponse */
        TimelineSummaryResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "generated" | "regenerated" | "already_generated" | "available";
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Schema Version */
            schema_version: number;
            /** Is Current Schema Version */
            is_current_schema_version: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Race Start Session Time Ms */
            race_start_session_time_ms: number;
            /** Event Count */
            event_count: number;
            /** Counts By Type */
            counts_by_type: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
        };
        /** TimingPoint */
        TimingPoint: {
            /** Lap Number */
            lap_number: number;
            /**
             * Race Time Ms
             * @description Race time at which the driver completed the lap
             */
            race_time_ms: number;
            /** Lap Time Ms */
            lap_time_ms: number | null;
            /**
             * Position
             * @description Lap-end classification position
             */
            position: number | null;
            /**
             * Gap To Leader Ms
             * @description Time behind the first driver to complete this lap number (lap-end basis); null when unknown
             */
            gap_to_leader_ms: number | null;
            /** Compound */
            compound: string | null;
            /** Tyre Age Laps */
            tyre_age_laps: number | null;
            /** Stint Number */
            stint_number: number | null;
            /** Is Pit In Lap */
            is_pit_in_lap: boolean | null;
            /** Is Pit Out Lap */
            is_pit_out_lap: boolean | null;
            /** Is Deleted */
            is_deleted: boolean | null;
            /**
             * Track Status
             * @description Track status when the lap was completed
             */
            track_status: string | null;
            /**
             * Sectors
             * @description Empty when no sector times exist
             */
            sectors: components["schemas"]["SectorOut"][];
        };
        /**
         * TrackStatus
         * @description Track status derived from FastF1 track-status codes.
         * @enum {string}
         */
        TrackStatus: "GREEN" | "YELLOW" | "SAFETY_CAR" | "VIRTUAL_SAFETY_CAR" | "VIRTUAL_SAFETY_CAR_ENDING" | "RED_FLAG" | "UNKNOWN";
        /** TrackStatusOut */
        TrackStatusOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Race Time Ms */
            race_time_ms: number;
            status: components["schemas"]["TrackStatus"];
            /** Source Code */
            source_code: string;
            /** Message */
            message: string | null;
            /** Sequence */
            sequence: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_seasons_api_v1_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonSummary"][];
                };
            };
        };
    };
    list_races_api_v1_races_get: {
        parameters: {
            query?: {
                season?: number | null;
                /** @description Championship round */
                round?: number | null;
                /** @description Case-insensitive name/location match */
                event?: string | null;
                /** @description Only races with this session imported */
                session_type?: components["schemas"]["SessionType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_api_v1_races__race_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_race_drivers_api_v1_races__race_id__drivers_get: {
        parameters: {
            query?: {
                /** @description Which session of the event (default: the race) */
                session_type?: components["schemas"]["SessionType"];
            };
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverSummary"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_race_laps_api_v1_races__race_id__laps_get: {
        parameters: {
            query?: {
                /** @description Driver abbreviation (case-insensitive) or UUID */
                driver?: string | null;
                /** @description Which session of the event (default: the race) */
                session_type?: components["schemas"]["SessionType"];
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
                /** @description First lap (inclusive) */
                lap_from?: number | null;
                /** @description Last lap (inclusive) */
                lap_to?: number | null;
            };
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_laps_api_v1_sessions__session_id__laps_get: {
        parameters: {
            query?: {
                /** @description Driver abbreviation (case-insensitive) or UUID */
                driver?: string | null;
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
                /** @description First lap (inclusive) */
                lap_from?: number | null;
                /** @description Last lap (inclusive) */
                lap_to?: number | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stints_api_v1_sessions__session_id__stints_get: {
        parameters: {
            query?: {
                /** @description Driver abbreviation (case-insensitive) or UUID */
                driver?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StintOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_track_status_api_v1_sessions__session_id__track_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackStatusOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_replay_api_v1_replays_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_replay_api_v1_replays__replay_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_replay_api_v1_replays__replay_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pause_replay_api_v1_replays__replay_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resume_replay_api_v1_replays__replay_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stop_replay_api_v1_replays__replay_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restart_replay_api_v1_replays__replay_id__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_replay_speed_api_v1_replays__replay_id__speed_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaySpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_race_state_api_v1_replays__replay_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceStateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_driver_state_api_v1_replays__replay_id__drivers__driver__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
                /** @description Driver abbreviation (case-insensitive) or UUID */
                driver: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverStateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_detected_events_api_v1_replays__replay_id__events_get: {
        parameters: {
            query?: {
                /** @description Repeatable; any of the given types */
                event_type?: components["schemas"]["DetectedEventType"][] | null;
                /** @description Driver abbreviation (case-insensitive) or UUID */
                driver?: string | null;
                /** @description Default: the latest run */
                run_id?: string | null;
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
                /** @description First lap (inclusive) */
                lap_from?: number | null;
                /** @description Last lap (inclusive) */
                lap_to?: number | null;
            };
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectedEventPageOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_detected_event_api_v1_replays__replay_id__events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectedEventOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_replay_timing_api_v1_replays__replay_id__timing_get: {
        parameters: {
            query?: {
                /** @description Repeatable abbreviation or UUID; default: all drivers */
                driver?: string[] | null;
                /** @description First lap (inclusive) */
                lap_from?: number | null;
                /** @description Last lap (inclusive) */
                lap_to?: number | null;
            };
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayTimingResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_driver_timing_api_v1_replays__replay_id__drivers__driver__timing_get: {
        parameters: {
            query?: {
                /** @description First lap (inclusive) */
                lap_from?: number | null;
                /** @description Last lap (inclusive) */
                lap_to?: number | null;
            };
            header?: never;
            path: {
                replay_id: string;
                /** @description Driver abbreviation (case-insensitive) or UUID */
                driver: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverTimingResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_race_api_v1_races_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RaceImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceImportResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_timeline_events_api_v1_sessions__session_id__timeline_get: {
        parameters: {
            query?: {
                /** @description Driver abbreviation filter */
                driver?: string | null;
                /** @description Repeatable */
                event_type?: components["schemas"]["EventType"][] | null;
                lap_from?: number | null;
                lap_to?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_timeline_api_v1_sessions__session_id__timeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TimelineGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_summary_api_v1_sessions__session_id__timeline_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
